// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/accounting.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountingService_Transfer_FullMethodName            = "/accounting.AccountingService/Transfer"
	AccountingService_GetBalance_FullMethodName          = "/accounting.AccountingService/GetBalance"
	AccountingService_ValidateTransaction_FullMethodName = "/accounting.AccountingService/ValidateTransaction"
	AccountingService_HealthCheck_FullMethodName         = "/accounting.AccountingService/HealthCheck"
	AccountingService_CheckLimits_FullMethodName         = "/accounting.AccountingService/CheckLimits"
	AccountingService_GetLimits_FullMethodName           = "/accounting.AccountingService/GetLimits"
	AccountingService_ProcessPayout_FullMethodName       = "/accounting.AccountingService/ProcessPayout"
)

// AccountingServiceClient is the client API for AccountingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountingService handles all core financial operations
// with type-safe contracts between Go API and Rust Core.
type AccountingServiceClient interface {
	// Transfer executes an atomic double-entry transfer between wallets
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	// GetBalance retrieves the current balance for a wallet
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	// ValidateTransaction checks if a transaction is valid without executing
	ValidateTransaction(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
	// Health check for service monitoring
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// CheckLimits validates if a transaction is within user limits
	CheckLimits(ctx context.Context, in *LimitCheckRequest, opts ...grpc.CallOption) (*LimitCheckResponse, error)
	// GetLimits retrieves current limit status for a user
	GetLimits(ctx context.Context, in *LimitsRequest, opts ...grpc.CallOption) (*LimitsResponse, error)
	// ProcessPayout handles external payouts (PromptPay, etc.)
	ProcessPayout(ctx context.Context, in *PayoutRequest, opts ...grpc.CallOption) (*PayoutResponse, error)
}

type accountingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountingServiceClient(cc grpc.ClientConnInterface) AccountingServiceClient {
	return &accountingServiceClient{cc}
}

func (c *accountingServiceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, AccountingService_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingServiceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, AccountingService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingServiceClient) ValidateTransaction(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, AccountingService_ValidateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AccountingService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingServiceClient) CheckLimits(ctx context.Context, in *LimitCheckRequest, opts ...grpc.CallOption) (*LimitCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LimitCheckResponse)
	err := c.cc.Invoke(ctx, AccountingService_CheckLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingServiceClient) GetLimits(ctx context.Context, in *LimitsRequest, opts ...grpc.CallOption) (*LimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LimitsResponse)
	err := c.cc.Invoke(ctx, AccountingService_GetLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountingServiceClient) ProcessPayout(ctx context.Context, in *PayoutRequest, opts ...grpc.CallOption) (*PayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayoutResponse)
	err := c.cc.Invoke(ctx, AccountingService_ProcessPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountingServiceServer is the server API for AccountingService service.
// All implementations must embed UnimplementedAccountingServiceServer
// for forward compatibility.
//
// AccountingService handles all core financial operations
// with type-safe contracts between Go API and Rust Core.
type AccountingServiceServer interface {
	// Transfer executes an atomic double-entry transfer between wallets
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	// GetBalance retrieves the current balance for a wallet
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	// ValidateTransaction checks if a transaction is valid without executing
	ValidateTransaction(context.Context, *TransferRequest) (*ValidationResponse, error)
	// Health check for service monitoring
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	// CheckLimits validates if a transaction is within user limits
	CheckLimits(context.Context, *LimitCheckRequest) (*LimitCheckResponse, error)
	// GetLimits retrieves current limit status for a user
	GetLimits(context.Context, *LimitsRequest) (*LimitsResponse, error)
	// ProcessPayout handles external payouts (PromptPay, etc.)
	ProcessPayout(context.Context, *PayoutRequest) (*PayoutResponse, error)
	mustEmbedUnimplementedAccountingServiceServer()
}

// UnimplementedAccountingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountingServiceServer struct{}

func (UnimplementedAccountingServiceServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedAccountingServiceServer) GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedAccountingServiceServer) ValidateTransaction(context.Context, *TransferRequest) (*ValidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateTransaction not implemented")
}
func (UnimplementedAccountingServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAccountingServiceServer) CheckLimits(context.Context, *LimitCheckRequest) (*LimitCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckLimits not implemented")
}
func (UnimplementedAccountingServiceServer) GetLimits(context.Context, *LimitsRequest) (*LimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLimits not implemented")
}
func (UnimplementedAccountingServiceServer) ProcessPayout(context.Context, *PayoutRequest) (*PayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPayout not implemented")
}
func (UnimplementedAccountingServiceServer) mustEmbedUnimplementedAccountingServiceServer() {}
func (UnimplementedAccountingServiceServer) testEmbeddedByValue()                           {}

// UnsafeAccountingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountingServiceServer will
// result in compilation errors.
type UnsafeAccountingServiceServer interface {
	mustEmbedUnimplementedAccountingServiceServer()
}

func RegisterAccountingServiceServer(s grpc.ServiceRegistrar, srv AccountingServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountingService_ServiceDesc, srv)
}

func _AccountingService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingService_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingServiceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingService_ValidateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingServiceServer).ValidateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingService_ValidateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingServiceServer).ValidateTransaction(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingService_CheckLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LimitCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingServiceServer).CheckLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingService_CheckLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingServiceServer).CheckLimits(ctx, req.(*LimitCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingService_GetLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingServiceServer).GetLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingService_GetLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingServiceServer).GetLimits(ctx, req.(*LimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountingService_ProcessPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingServiceServer).ProcessPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingService_ProcessPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingServiceServer).ProcessPayout(ctx, req.(*PayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountingService_ServiceDesc is the grpc.ServiceDesc for AccountingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accounting.AccountingService",
	HandlerType: (*AccountingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _AccountingService_Transfer_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _AccountingService_GetBalance_Handler,
		},
		{
			MethodName: "ValidateTransaction",
			Handler:    _AccountingService_ValidateTransaction_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AccountingService_HealthCheck_Handler,
		},
		{
			MethodName: "CheckLimits",
			Handler:    _AccountingService_CheckLimits_Handler,
		},
		{
			MethodName: "GetLimits",
			Handler:    _AccountingService_GetLimits_Handler,
		},
		{
			MethodName: "ProcessPayout",
			Handler:    _AccountingService_ProcessPayout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/accounting.proto",
}
