// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: fx.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FXService_Convert_FullMethodName             = "/fx.FXService/Convert"
	FXService_GetRate_FullMethodName             = "/fx.FXService/GetRate"
	FXService_GetAllRates_FullMethodName         = "/fx.FXService/GetAllRates"
	FXService_HealthCheck_FullMethodName         = "/fx.FXService/HealthCheck"
	FXService_UpdateRate_FullMethodName          = "/fx.FXService/UpdateRate"
	FXService_VerifySignature_FullMethodName     = "/fx.FXService/VerifySignature"
	FXService_GetLimits_FullMethodName           = "/fx.FXService/GetLimits"
	FXService_PreValidateTransfer_FullMethodName = "/fx.FXService/PreValidateTransfer"
)

// FXServiceClient is the client API for FXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FXServiceClient interface {
	// Convert amount from one currency to another
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	// Get current exchange rate
	GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateResponse, error)
	// Get all available rates for a base currency
	GetAllRates(ctx context.Context, in *AllRatesRequest, opts ...grpc.CallOption) (*AllRatesResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *FXHealthRequest, opts ...grpc.CallOption) (*FXHealthResponse, error)
	// Admin/Control Plane: Update rate manually
	UpdateRate(ctx context.Context, in *UpdateRateRequest, opts ...grpc.CallOption) (*UpdateRateResponse, error)
	// Cryptography: Offload signature verification to Rust (Ed25519-SIMD)
	VerifySignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error)
	// Limits: Get remaining limits for user (Fast Path for UI)
	GetLimits(ctx context.Context, in *GetLimitsRequest, opts ...grpc.CallOption) (*GetLimitsResponse, error)
	// Pre-Validation: Combined Signature + Amount + Limits Check (Fast Path for Payment)
	PreValidateTransfer(ctx context.Context, in *PreValidateTransferRequest, opts ...grpc.CallOption) (*PreValidateTransferResponse, error)
}

type fXServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFXServiceClient(cc grpc.ClientConnInterface) FXServiceClient {
	return &fXServiceClient{cc}
}

func (c *fXServiceClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, FXService_Convert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateResponse, error) {
	out := new(RateResponse)
	err := c.cc.Invoke(ctx, FXService_GetRate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) GetAllRates(ctx context.Context, in *AllRatesRequest, opts ...grpc.CallOption) (*AllRatesResponse, error) {
	out := new(AllRatesResponse)
	err := c.cc.Invoke(ctx, FXService_GetAllRates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) HealthCheck(ctx context.Context, in *FXHealthRequest, opts ...grpc.CallOption) (*FXHealthResponse, error) {
	out := new(FXHealthResponse)
	err := c.cc.Invoke(ctx, FXService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) UpdateRate(ctx context.Context, in *UpdateRateRequest, opts ...grpc.CallOption) (*UpdateRateResponse, error) {
	out := new(UpdateRateResponse)
	err := c.cc.Invoke(ctx, FXService_UpdateRate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) VerifySignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error) {
	out := new(VerifySignatureResponse)
	err := c.cc.Invoke(ctx, FXService_VerifySignature_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) GetLimits(ctx context.Context, in *GetLimitsRequest, opts ...grpc.CallOption) (*GetLimitsResponse, error) {
	out := new(GetLimitsResponse)
	err := c.cc.Invoke(ctx, FXService_GetLimits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fXServiceClient) PreValidateTransfer(ctx context.Context, in *PreValidateTransferRequest, opts ...grpc.CallOption) (*PreValidateTransferResponse, error) {
	out := new(PreValidateTransferResponse)
	err := c.cc.Invoke(ctx, FXService_PreValidateTransfer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FXServiceServer is the server API for FXService service.
// All implementations must embed UnimplementedFXServiceServer
// for forward compatibility
type FXServiceServer interface {
	// Convert amount from one currency to another
	Convert(context.Context, *ConvertRequest) (*ConvertResponse, error)
	// Get current exchange rate
	GetRate(context.Context, *RateRequest) (*RateResponse, error)
	// Get all available rates for a base currency
	GetAllRates(context.Context, *AllRatesRequest) (*AllRatesResponse, error)
	// Health check
	HealthCheck(context.Context, *FXHealthRequest) (*FXHealthResponse, error)
	// Admin/Control Plane: Update rate manually
	UpdateRate(context.Context, *UpdateRateRequest) (*UpdateRateResponse, error)
	// Cryptography: Offload signature verification to Rust (Ed25519-SIMD)
	VerifySignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error)
	// Limits: Get remaining limits for user (Fast Path for UI)
	GetLimits(context.Context, *GetLimitsRequest) (*GetLimitsResponse, error)
	// Pre-Validation: Combined Signature + Amount + Limits Check (Fast Path for Payment)
	PreValidateTransfer(context.Context, *PreValidateTransferRequest) (*PreValidateTransferResponse, error)
	mustEmbedUnimplementedFXServiceServer()
}

// UnimplementedFXServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFXServiceServer struct {
}

func (UnimplementedFXServiceServer) Convert(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedFXServiceServer) GetRate(context.Context, *RateRequest) (*RateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRate not implemented")
}
func (UnimplementedFXServiceServer) GetAllRates(context.Context, *AllRatesRequest) (*AllRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRates not implemented")
}
func (UnimplementedFXServiceServer) HealthCheck(context.Context, *FXHealthRequest) (*FXHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFXServiceServer) UpdateRate(context.Context, *UpdateRateRequest) (*UpdateRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRate not implemented")
}
func (UnimplementedFXServiceServer) VerifySignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySignature not implemented")
}
func (UnimplementedFXServiceServer) GetLimits(context.Context, *GetLimitsRequest) (*GetLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLimits not implemented")
}
func (UnimplementedFXServiceServer) PreValidateTransfer(context.Context, *PreValidateTransferRequest) (*PreValidateTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreValidateTransfer not implemented")
}
func (UnimplementedFXServiceServer) mustEmbedUnimplementedFXServiceServer() {}

// UnsafeFXServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FXServiceServer will
// result in compilation errors.
type UnsafeFXServiceServer interface {
	mustEmbedUnimplementedFXServiceServer()
}

func RegisterFXServiceServer(s grpc.ServiceRegistrar, srv FXServiceServer) {
	s.RegisterService(&FXService_ServiceDesc, srv)
}

func _FXService_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_GetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).GetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_GetRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).GetRate(ctx, req.(*RateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_GetAllRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).GetAllRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_GetAllRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).GetAllRates(ctx, req.(*AllRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FXHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).HealthCheck(ctx, req.(*FXHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_UpdateRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).UpdateRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_UpdateRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).UpdateRate(ctx, req.(*UpdateRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_VerifySignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).VerifySignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_VerifySignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).VerifySignature(ctx, req.(*VerifySignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_GetLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).GetLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_GetLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).GetLimits(ctx, req.(*GetLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FXService_PreValidateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreValidateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXServiceServer).PreValidateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXService_PreValidateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXServiceServer).PreValidateTransfer(ctx, req.(*PreValidateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FXService_ServiceDesc is the grpc.ServiceDesc for FXService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FXService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fx.FXService",
	HandlerType: (*FXServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _FXService_Convert_Handler,
		},
		{
			MethodName: "GetRate",
			Handler:    _FXService_GetRate_Handler,
		},
		{
			MethodName: "GetAllRates",
			Handler:    _FXService_GetAllRates_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _FXService_HealthCheck_Handler,
		},
		{
			MethodName: "UpdateRate",
			Handler:    _FXService_UpdateRate_Handler,
		},
		{
			MethodName: "VerifySignature",
			Handler:    _FXService_VerifySignature_Handler,
		},
		{
			MethodName: "GetLimits",
			Handler:    _FXService_GetLimits_Handler,
		},
		{
			MethodName: "PreValidateTransfer",
			Handler:    _FXService_PreValidateTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fx.proto",
}
