// File generated by Antigravity based on Firebase Console data.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_lite_runtime_classes
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZD2ASI_95rC0yJSfDllyuEHeMvwX5kgc',
    appId:
        '1:93085559291:web:53198647acae91f16ec35e', // Dummy web app ID from console registration
    messagingSenderId: '93085559291',
    projectId: 'my-paysify-project',
    authDomain: 'my-paysify-project.firebaseapp.com',
    storageBucket: 'my-paysify-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZD2ASI_95rC0yJSfDllyuEHeMvwX5kgc',
    appId: '1:93085559291:android:9753d90b1a6e99f96ec35e',
    messagingSenderId: '93085559291',
    projectId: 'my-paysify-project',
    storageBucket: 'my-paysify-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZD2ASI_95rC0yJSfDllyuEHeMvwX5kgc',
    appId: '1:93085559291:ios:a9dfaadc836e256a6ec35e',
    messagingSenderId: '93085559291',
    projectId: 'my-paysify-project',
    storageBucket: 'my-paysify-project.firebasestorage.app',
    iosBundleId: 'com.methas.paysif',
  );
}
