-- ============================================================================
-- AUTO-SYNC CRON JOB (Bypassed for standard Postgres compatibility)
-- ============================================================================
-- pg_cron is not available on standard Postgres Docker containers.
-- This file is left empty to allow migrations to complete successfully.
